config/routes.rb
Rails.application.routes.draw do  

  root :to => 'auctions#index'

  resources :user_sessions
  resources :users
  resources :password_resets
  resources :searchs
  resources :statistics
  
  resources :auctions do
    resources :bids, only: :create
  end
  
  resources :bids, only: [:index, :edit, :update] do
    patch :elegir, on: :member
  end

	get '/auction/myAuctions', to: 'auctions#myAuctions'
  get '/auction/finalizar', to: 'auctions#finalizar'
  get '/auction/finalizadas', to: 'auctions#finalizadas'
  get '/auction/ganadas', to: 'auctions#ganadas'

  resources :categories

  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout	

end

app/models/auction.rb
class Auction < ActiveRecord::Base
	belongs_to :user
  belongs_to :category
  has_many :bids

	validates :name, presence: true
	validates_format_of :name, :with => /[a-z\s]/i, :message => "can only contain letters and numbers."

	validates :description, presence: true
	validates_format_of :description, :with => /./

  def user_owner?(current_user)
    if current_user.id == self.user_id || current_user.admin?
        return true
      end

    return false
  end

  dragonfly_accessor :image  #defines a reader/writer for image
end

app/controllers/auctions_controller.rb
class AuctionsController < ApplicationController
  before_action :require_login, only: [ :new, :create, :edit, :update, :destroy ]
  before_action :get_auction, only: [:show, :edit, :update, :destroy]
  authorize_resource #con esta linea sin comentar, no puedo acceder a "Mis Subastas"
  respond_to :html, :xml, :json

  def index
    @auction = Auction.where(active: true)
  end

  def myAuctions 
    #@auction = Auction.all  
  end

  def finalizar
    @auction = Auction.where("ends_at <= ?", Time.now)
    @auction = @auction.where(user_id: current_user.id, active: true)
  end

  def finalizadas
    @auction = Auction.where.not(bid_ganador: nil)
    @auction = @auction.where(user_id: current_user.id, active: false)
  end

  def ganadas    
    @auction = Auction.where(user_ganador: current_user.id, active: false)
  end

  def show
    #@bid = @auction.bids.build
    @bid = Bid.new
  end

 	def new
    @auction = Auction.new
  end

  def create
    @auction = Auction.new(auction_params)
    @auction.user_id = current_user.id 
    @auction.ends_at = Time.now + 20.days

    if @auction.save
      redirect_to(:auctions, notice: 'Subasta creada con éxito!')
    else
      render action: 'new'	
    end
  end  
 
  def edit   
  end

  def update 
		if @auction.update(auction_params)
		  redirect_to(:auctions, notice: 'Subasta actualizada con éxito!')
		else
		  render 'edit'
		end
  end

  def destroy
  	@auction.active = false
  	@auction.save
  	redirect_to(:auctions, notice: 'Subasta eliminada con éxito!')  	
  end


  private
  
    def get_auction
      @auction = Auction.find(params[:id])
    end  

    def auction_params
      params.require(:auction).permit(:name, :description, :category_id, :image)
    end
end

app/helpers/auctions_helper.rb
module AuctionsHelper
end

app/views/auctions/_bids_form.html.erb
<% if current_user %>
    <% if current_user == @auction.user && !@auction.active? && @auction.bid_ganador != nil %>
      <h3>Oferta ganadora</h3>
      <div class="span2 well">
      <% user_ganador = User.find(@auction.user_ganador) %>
      <% bid_ganador = Bid.find(@auction.bid_ganador) %>
      <p><strong><%= user_ganador.username %></strong> <%= bid_ganador.created_at.to_formatted_s(:db) %></p>
      <p><%= bid_ganador.reason %></p>
          </div>
  	<% elsif current_user == @auction.user && @auction.ends_at <= Time.now %> 
    	<h3>Razones de oferta</h3>

    	<% @auction.bids.each do |bid| %>
    		<div class="span2 well">
        		<p><strong><%= bid.user.username %></strong> <%= bid.created_at.to_formatted_s(:db) %> <%= link_to "Elegir oferta", elegir_bid_path(bid), method: :patch, class: "btn btn-success", data: { confirm: "¿Desea que la oferta seleccionada sea la ganadora?" } %> </p>
        		<p><%= bid.reason %></p>
      		</div>
    	<% end %>

    <% elsif current_user == @auction.user %> 
      <h3>Razones de oferta</h3>

      <% @auction.bids.each do |bid| %>
        <div class="span2 well">
            <p><strong><%= bid.user.username %></strong> <%= bid.created_at.to_formatted_s(:db) %></p>
            <p><%= bid.reason %></p>
          </div>
      <% end %>

  	<% elsif current_user.has_bids?(@auction) %>

    	<h3>Razón de mi oferta</h3>

    	<div class="span2 well">
    		<p><strong><%= current_user.username %></strong> <%= current_user.get_created_at(@auction).to_formatted_s(:db) %> <span class="btn btn-success"><%= number_to_currency(current_user.get_price(@auction)) %></span>
        	<% @auction.bids.each do |bid| %>
        		<% if  current_user.id == bid.user_id && @auction.active? %>
            		<%= link_to "Editar Oferta", edit_bid_path(bid), class: 'btn btn-primary' %>
          		<% end %>
        	<% end %>  
      		</p>
      		<p><%= current_user.get_reason(@auction) %></p>
    	</div>

    <% else %>
	    <% if !current_user.has_bids?(@auction) %>
    		<h3>Publica tu oferta:</h3>
    
    		<% if @bid.errors.any? %>
    			<div id="error_explanation">
        			<ul>
        				<% @bid.errors.full_messages.each do |message| %>
            				<li><%= message %></li>
          				<% end %>
        			</ul>
      			</div>

    		<% end %>
    	  
    	    <%= form_for(@bid, url: auction_bids_path(@auction)) do |f| %>
	        	<div class="form-group">
	            	<%= f.label :reason, "Razón" %>
	            	<%= f.text_area :reason, class: "form-control" %>
	        	</div>  

	        	<div class="form-group">
	        	    <%= f.label :price, "Precio" %>
	        	    <%= f.text_field :price, class: "form-control", placeholder: "Ej. 256.64" %>
	        	</div>        
	
	           <%= f.submit "Ofertar", class: "btn btn-primary" %>
    	    <% end %>
   		<% end %>
    <% end %>
<% end %>

app/views/auctions/_form.html.erb
<%= form_for @auction do |f| %>

  <% if @auction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@auction.errors.count, "error") %> prohibited this auction from being saved:</h2>
      <ul>
	      <% @auction.errors.full_messages.each do |message| %>
					<li><%= message %></li>
      	<% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label "Nombre" %>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label "Descripción" %>
    <%= f.text_area :description, class: "form-control" %>
  </div>

	<div class="form-group">
		<%= f.label "Categoría" %>
		<%= f.select :category_id, options_from_collection_for_select(Category.all, :id, :name, 25), {}, class: "form-control" %>
	</div>

  <% if @auction.new_record? %>
    <div class="form-group">
      <%= f.label "Imagen" %>
      <%= f.file_field :image, class: "form-control" %>
    </div> 
  <% end %>

  <div class="actions">
  	<%= link_to 'Cancelar', auctions_path, class: "btn btn-danger" %>
    <% if @auction.new_record? %>
      <%= f.submit "Crear subasta", class: "btn btn-primary" %>
    <% else %>
      <%= f.submit "Guardar cambios", class: "btn btn-primary" %>
    <% end %>    
  </div>

<% end %>

app/views/auctions/_tabs.html.erb
<% if current_user %>
	<ul class="nav nav-tabs">
	  <li class="<%= 'active' if current_page?('/auctions') || current_page?(root_path) %>"><%= link_to "Ver todas", auctions_path %></li>

	  <% if current_user %>
	    <li class="<%= 'active' if current_page?('/auctions/new') %>"><%= link_to "Crear Subasta", new_auction_path %></li>
	    <li class="<%= 'active' if current_page?('/auction/myAuctions') %>"><%= link_to "Mis Subastas", auction_myAuctions_path %></li>
	    <li class="<%= 'active' if current_page?('/bids/index') %>"><%= link_to "Mis Ofertas", bids_path %></li>
      <li class="<%= 'active' if current_page?('/auction/finalizar') %>"><%= link_to "Finalizar", auction_finalizar_path %></li>
      <li class="<%= 'active' if current_page?('/auction/finalizadas') %>"><%= link_to "Finalizadas", auction_finalizadas_path %></li>
      <li class="<%= 'active' if current_page?('/auction/ganadas') %>"><%= link_to "Ganadas", auction_ganadas_path %></li>
	  <% end %>
	</ul>
<% end %>

app/views/auctions/backup_bids_form.html.erb
<% if current_user %>
  
  <% if @auction.user == current_user %>

    <h3>Razones de oferta</h3>

    <% @auction.bids.each do |b| %>
      <div class="span2 well">
				<if b.user_id != 0>
					<%= User.find(4).username %>
          <%= b.reason %>
				<% end %>
      </div>
    <% end %>

  <% elsif current_user.bids.from_auction(@auction).exists? %>
  
    <h3>Razón de mi oferta</h3>

    <%= current_user.bid_from_auction(@auction).reason %>

  <% else %>

    <%# !Bid.exists?(user_id: current_user.id, auction_id: @auction.id) %>
    <% if !current_user.oferto_en?(@auction) %>
      <h3>Publica tu oferta:</h3>

      <%#= form_for([@auction, @auction.bids.build]) do |f| %>
      <%= form_for(@bid, url: auction_bids_path(@auction)) do |f| %>

      <%#= form_for @auction do |f| %>
      <!-- UPDATE /auctions/1 -->

      <%#= form_for @auction.bids.build do |f| %>
      <%#= form_for @bid do |f| %>
      <!-- CREATE /bids -->

      <%#= form_for([@auction, @auction.bids.build]) do |f| %>
      <%#= form_for(@bid, url: auction_bids_path(@auction)) do |f| %>
      <!-- CREATE /auctions/1/bids -->

        <div class="form-group">
          <%= f.text_area :reason, class: "form-control" %>
        </div>

        <%= f.submit "Ofertar" %>
      <% end %>
    <% end %>

  <% end %>
<% end %>

app/views/auctions/edit.html.erb
<%= link_to 'Volver al listado', auctions_path %> | Publicación #<%= @auction.id %>

<h1>Editar Subasta</h1>  

<%= render 'form' %> 

app/views/auctions/finalizadas.html.erb
<h1>Finalizar</h1>

<%= render 'tabs' %>

<table class="table table-striped">
  <thead>
    <tr>
      <th class="col-sm-2">Nombre</th>
      <th class="col-sm-3">Descripcion</th>
      <th class="col-sm-2">Categoria</th>
      <th class="col-sm-1">Inicio</th>
      <th class="col-sm-1">Fin</th>
      <th class="col-sm-1">Subastador</th>
      <th class="col-sm-2">Acción</th>
    </tr>
  </thead>

  <tbody>
    <% @auction.each do |a| %>
        <tr>
          <td><%= a.name %></td>
          <td><%= truncate(a.description, length: 120, omission: '...') %></td>
          <td><%= a.category.name %></td>
          <td><%= a.created_at.strftime("%d %b. %Y") %></td>
          <td><%= a.ends_at.strftime("%d %b. %Y") %></td>
          <td><%= a.user.username %></td>
          <td><%= link_to 'Ver', auction_path(a), class: 'btn btn-warning' %></td>
        </tr>
    <% end %>  
  </tbody>
</table>

app/views/auctions/finalizar.html.erb
<h1>Finalizar</h1>

<%= render 'tabs' %>

<table class="table table-striped">
  <thead>
    <tr>
      <th class="col-sm-2">Nombre</th>
      <th class="col-sm-3">Descripcion</th>
      <th class="col-sm-2">Categoria</th>
      <th class="col-sm-1">Inicio</th>
      <th class="col-sm-1">Fin</th>
      <th class="col-sm-1">Subastador</th>
      <th class="col-sm-2">Acción</th>
    </tr>
  </thead>

  <tbody>
    <% @auction.each do |a| %>
        <tr>
          <td><%= a.name %></td>
          <td><%= truncate(a.description, length: 120, omission: '...') %></td>
          <td><%= a.category.name %></td>
          <td><%= a.created_at.strftime("%d %b. %Y") %></td>
          <td><%= a.ends_at.strftime("%d %b. %Y") %></td>
          <td><%= a.user.username %></td>

          <td>
            <%= link_to 'Ver', auction_path(a), class: 'btn btn-warning' %>       
            <% if current_user %>
              <% if a.user_owner?(current_user) %>                
                <%= link_to "Eliminar", a, method: :delete, data: { confirm:"¿Está seguro?" }, class: 'btn btn-danger' if can?(:destroy, a) %>  
              <% end %>
            <% end %>

          </td>
        </tr>
    <% end %>  
  </tbody>
</table>

app/views/auctions/ganadas.html.erb
<h1>Finalizar</h1>

<%= render 'tabs' %>

<table class="table table-striped">
  <thead>
    <tr>
      <th class="col-sm-2">Nombre</th>
      <th class="col-sm-3">Descripcion</th>
      <th class="col-sm-2">Categoria</th>
      <th class="col-sm-1">Inicio</th>
      <th class="col-sm-1">Fin</th>
      <th class="col-sm-1">Subastador</th>
      <th class="col-sm-2">Acción</th>
    </tr>
  </thead>

  <tbody>
    <% @auction.each do |a| %>
        <tr>
          <td><%= a.name %></td>
          <td><%= truncate(a.description, length: 120, omission: '...') %></td>
          <td><%= a.category.name %></td>
          <td><%= a.created_at.strftime("%d %b. %Y") %></td>
          <td><%= a.ends_at.strftime("%d %b. %Y") %></td>
          <td><%= a.user.username %></td>
          <td><%= link_to 'Ver', auction_path(a), class: 'btn btn-warning' %></td>
        </tr>
    <% end %>  
  </tbody>
</table>

app/views/auctions/index.html.erb
<h1>Subastas</h1>

<%= render 'tabs' %>

<table class="table table-striped">
	<thead>
		<tr>
			<th class="col-sm-2">Nombre</th>
			<th class="col-sm-3">Descripcion</th>
			<th class="col-sm-2">Categoria</th>
			<th class="col-sm-1">Inicio</th>
			<th class="col-sm-1">Fin</th>
			<th class="col-sm-1">Subastador</th>
			<th class="col-sm-2">Acción</th>
		</tr>
	</thead>

	<tbody>
		<% @auction.each do |a| %>
			<% if Time.now < a.ends_at %>
		<%# Auction.all.each do |a| %>
			<%# if a.active %>
				<tr>
					<td><%= a.name %></td>
					<td><%= truncate(a.description, length: 120, omission: '...') %></td>
					<td><%= a.category.name %></td>
					<td><%= a.created_at.strftime("%d %b. %Y") %></td>
					<td><%= a.ends_at.strftime("%d %b. %Y") %></td>
					<td><%= a.user.username %></td>

					<td>
						<%= link_to 'Ver', auction_path(a), class: 'btn btn-warning' %>				
						<% if current_user %>
							<% if a.user_owner?(current_user) %>
								<% if  a.bids.empty? %>
									<%= link_to 'Editar', edit_auction_path(a), class: 'btn btn-primary' if can?(:update, a) %>
								<%end%>
								
								<%= link_to "Eliminar", a, method: :delete, data: { confirm:"¿Está seguro?" }, class: 'btn btn-danger' if can?(:destroy, a) %>	
							<% end %>
						<% end %>

					</td>
				</tr>
			<% end %>
		<% end %>  
	</tbody>
</table>

app/views/auctions/myAuctions.html.erb
<h1>Mis Subastas</h1>

<%= render 'tabs' %>

<table class="table table-striped">
	<thead>
		<tr>
			<th class="col-sm-2">Nombre</th>
			<th class="col-sm-2">Descripcion</th>
			<th class="col-sm-2">Categoria</th>
			<th class="col-sm-1">Ofertas</th>
			<th class="col-sm-1">Inicio</th>
			<th class="col-sm-1">Fin</th>
			<th class="col-sm-3">Acción</th>
		</tr>
	</thead>

	<tbody>
		<% current_user.get_auctions.each do |a| %>
			<%# if a.user == current_user%>
				<%# if a.active %>
					<tr>
						<td><%= a.name %></td>
						<td><%= truncate(a.description, length: 120, omission: '...') %></td>
						<td><%= a.category.name %></td>
						<% m=0 %>						
						<% Bid.all.each do |b| %>
							<% if b.auction_id == a.id%>
								<% m=m+1 %>
							<% end %>
						<% end %>
						<td><%= m %></td>
						<td><%= a.created_at.strftime("%d %b. %Y") %></td>
						<td><%= a.ends_at.strftime("%d %b. %Y") %></td>

						<td>
							<%= link_to 'Ver', auction_path(a), class: 'btn btn-warning' %>				
							<% if current_user %>
								<% if a.user_owner?(current_user) %>
									<% if  a.bids.empty? %>
										<%= link_to 'Editar', edit_auction_path(a), class: 'btn btn-primary' if can?(:update, a) %>
									<%end%>
								
									<%= link_to "Eliminar", a, method: :delete, data: { confirm:"¿Está seguro?" }, class: 'btn btn-danger' if can?(:destroy, a) %>	
								<% end %>
							<% end %>

						</td>
					</tr>
				<%# end %>
			<%# end %>
		<% end %>  
	</tbody>
</table>

app/views/auctions/new.html.erb
<h1>Nueva Subasta</h1>

<%= render 'tabs' %>
<%= render 'form' %>

app/views/auctions/show.html.erb
<%= link_to 'Volver al listado', auctions_path %> | Publicación #<%= @auction.id %>

<div class="page-header">
	<h1><%= @auction.name %> <small><%= @auction.category.name %></small></h1>
</div>

<div class="row">
  <div class="col-md-4">
    <%= image_tag @auction.image.thumb('400x400').url if Auction.first.image_stored? %>
  </div>
  <div>
	
  </div>
  <div class="col-md-8">
    <h3>Autor</h3>
    <%= @auction.user.username %>

    <h3>Descripción</h3>
    <%= @auction.description %>

    <h3>Fin de la subasta</h3>
    <%= @auction.ends_at.strftime("%d %b. %Y") %>
  </div>
</div>

<%= render 'auctions/bids_form' %>