config/routes.rb
Rails.application.routes.draw do  

  root :to => 'auctions#index'

  resources :user_sessions
  resources :users
  resources :password_resets
  resources :searchs
  resources :statistics
  
  resources :auctions do
    resources :bids, only: :create
  end
  
  resources :bids, only: [:index, :edit, :update] do
    patch :elegir, on: :member
  end

	get '/auction/myAuctions', to: 'auctions#myAuctions'
  get '/auction/finalizar', to: 'auctions#finalizar'
  get '/auction/finalizadas', to: 'auctions#finalizadas'
  get '/auction/ganadas', to: 'auctions#ganadas'

  resources :categories

  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout	

end

app/models/category.rb
class Category < ActiveRecord::Base  
  has_many :auctions

	validates :name, presence: true, uniqueness: true, length: { maximum: 30 }

	default_scope -> {order(:name)}  

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_login, only: [ :new, :create, :edit, :update, :destroy ]
  before_action :get_category, only: [ :edit, :update, :destroy, :show ]

  #authorize_resource

  respond_to :html, :xml, :json

  def index
    @category = Category.all
  end

  def new
    @category = Category.new
  end

  def create
  	@category = Category.new(category_params)

    if @category.save
      redirect_to(:categories, notice: "Categoría '#{@category.name}' creada con éxito!")
    else
      render 'new'
    end
  end

  def edit    
  end

  def show    
  end

  def update
    name = @category.name

    if @category.update(category_params)
      redirect_to(:categories, notice: "Categoría '#{name}' actualizada a '#{@category.name}'")
    else
      render 'edit'
    end
  end

  def destroy  	
    @category.active = !@category.active
    @category.save

    if @category.active
      redirect_to(:categories, notice: "Categoría '#{@category.name}' desactivada!")
    else
      redirect_to(:categories, notice: "Categoría '#{@category.name}' activada!")
    end
  end  


  private

    def get_category
      @category = Category.find(params[:id])
    end

    def category_params
      params.require(:category).permit(:name)
    end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<% if @category.errors.any?  %>
	<div class="alert alert-danger" role="alert">
		<%= @category.errors.get(:name).first %>
	</div>
<% end %>

<%= form_for @category do |f| %>		
	<div class="form-group">
		<%= f.label :Name %>
		<%= f.text_field :name, class: 'form-control', placeholder: 'Ej: muebles, vestimentas, etc.' %>
	</div>

	<%= link_to "Cancelar", categories_path, class: 'btn btn-danger' %>
	<%= f.submit "Guardar", class: 'btn btn-primary' %>			
<% end %>

app/views/categories/_tabs.html.erb
<% if current_user %>
	<% if current_user.admin? %>
		<ul class="nav nav-tabs">
		  <li class="<%= 'active' if current_page?(:controller => 'categories', :action => 'index') %>"><%= link_to "Ver todas", categories_path %></li>
			<li class="<%= 'active' if current_page?(:controller => 'categories', :action => 'new') %>"><%= link_to "Crear categoría", new_category_path %></li>
		</ul>
	<% end %>
<% end %>

app/views/categories/edit.html.erb
<h1>Editar Categorias</h1>

<%= render 'form' %>

app/views/categories/index.html.erb
<h1>Categorias</h1>

<%= render 'tabs' %>

<table class="table table-striped">
	<thead>
		<tr>
			<th class="col-sm-8">Nombre</th>
			<th class="col-sm-4">Acción</th>
			
		</tr>
	</thead>

	<tbody>
		<% @category.each do |category| %>
			<tr>
				<td><%= category.name %></td>
				<td>
						<%= link_to "Ver", category_path(category), class: 'btn btn-warning' %>
					<% if current_user %>
						<% if current_user.admin? %>
							<%= link_to "Editar", edit_category_path(category), class: 'btn btn-primary' %>					
						  
							<% if category.active %>
								<%= link_to "Desactivar", category, method: :delete, data:{confirm:"¿Está seguro que desea borrar la categoria seleccionada?"}, class: 'btn btn-danger' %>
							<% else %>
								<%= link_to "Activar", category, method: :delete, class: 'btn btn-success' %>
							<% end %>
						<% end %>
					<% end %>

				</td>
			</tr>
		<% end %>  
	</tbody>
</table>

app/views/categories/new.html.erb
<h1>Categorias</h1>

<%= render 'tabs' %>
<%= render 'form' %>

app/views/categories/show.html.erb
<%= link_to 'Volver al listado', categories_path %>

<div class="page-header">
  <h1><%= @category.name %></h1>
</div>

<table class="table table-striped">
	<thead>
		<tr>
			<th class="col-sm-2">Nombre</th>
			<th class="col-sm-5">Descripcion</th>
			<th class="col-sm-1">Inicio</th>
			<th class="col-sm-1">Subastador</th>
			<th class="col-sm-3">Acción</th>
		</tr>
	</thead>

	<tbody>
		<% Auction.all.each do |a| %>
			<% if a.active %>
				<% if a.category.name == @category.name%>
					<tr>
						<td><%= a.name %></td>
						<td><%= truncate(a.description, length: 120, omission: '...') %></td>
						<td><%= a.category.name %></td>
						<td><%= a.user.username %></td>

						<td>
							<%= link_to 'Ver', auction_path(a), class: 'btn btn-warning' %>				
							<% if current_user %>
								<% if a.user_owner?(current_user) %>
									<% if  a.bids.empty? %>
										<%= link_to 'Editar', edit_auction_path(a), class: 'btn btn-primary' if can?(:update, a) %>
									<%end%>
								
									<%= link_to "Eliminar", a, method: :delete, data: { confirm:"¿Está seguro?" }, class: 'btn btn-danger' if can?(:destroy, a) %>	
								<% end %>
							<% end %>

						</td>
					</tr>
				<% end %>
			<% end %>
		<% end %>  
	</tbody>
</table>