config/routes.rb
Rails.application.routes.draw do  

  root :to => 'auctions#index'

  resources :user_sessions
  resources :users
  resources :password_resets
  resources :searchs
  resources :statistics
  
  resources :auctions do
    resources :bids, only: :create
  end
  
  resources :bids, only: [:index, :edit, :update] do
    patch :elegir, on: :member
  end

	get '/auction/myAuctions', to: 'auctions#myAuctions'
  get '/auction/finalizar', to: 'auctions#finalizar'
  get '/auction/finalizadas', to: 'auctions#finalizadas'
  get '/auction/ganadas', to: 'auctions#ganadas'

  resources :categories

  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout	

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  rescue_from CanCan::AccessDenied, with: :access_denied

  # before_filter :require_login

  private

  def not_authenticated
  	redirect_to login_path, alert: 'Por favor, inicia sesión primero'
  end

  def access_denied
  	redirect_to root_path, alert: 'No tenés permisos para acceder.'
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
	def flash_class(level)
		case level
			when 'notice' then "alert alert-info"
			when 'success' then "alert alert-success"
			when 'error' then "alert alert-error"
			when 'alert' then "alert alert-danger"
		end			
	end
end

app/views/application/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a id="navbar-brand" class="navbar-brand" href="<%= '/auctions' %>"><%= image_tag('logo.png', size: '124x43', alt: "Logo de Bestnid")%></a>
    </div>

    <%= form_tag("/searchs/index", method: "get", class: "navbar-form navbar-left") do %>
      <div class="form-group">
        <%= text_field_tag :name, nil, class: "form-control" %>
        <%#= select_tag :category_id , options_from_collection_for_select(Category.all, :id, :name, 0), :include_blank => true, class: "form-control" %>  
        <%= select_tag :category_id , options_from_collection_for_select(Category.all, :id, :name, 0), :prompt => "Todas las categorías", class: "form-control" %>  
      </div>

      <%= submit_tag "Buscar", class: "btn btn-default" %> 
    <% end %>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      
    	<ul class="nav navbar-nav navbar-right">
      	<li><%= link_to "Subastas",  auctions_path %></li>

      	<% if current_user %>

      		<% if current_user.admin? %>          
      			<li><%= link_to "Usuarios", users_path %></li>
      			<li><%= link_to "Estadisticas", new_statistic_path %></li>
            <li><%= link_to "Categorias" , categories_path %></li>
      		<% end %>

      		<li><%= link_to "Nueva Subasta",  new_auction_path %></li>   	

          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false" style="font-weight: bold"><%= current_user.username %><span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to "Editar perfil", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li><%= link_to "Salir", :logout, method: :post %></li> 
            </ul>
          </li>

      	<% else %>
      		<li><%= link_to "Regístrate", new_user_path %></li>
      		<li><%= link_to "Ingresa", :login %></li>
    	<% end %>
        <!--- <li><a href="#"><span class="glyphicon glyphicon-question-sign"><%# ayuda_path %></span></a></li> -->
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>