config/routes.rb
Rails.application.routes.draw do  

  root :to => 'auctions#index'

  resources :user_sessions
  resources :users
  resources :password_resets
  resources :searchs
  resources :statistics
  
  resources :auctions do
    resources :bids, only: :create
  end
  
  resources :bids, only: [:index, :edit, :update] do
    patch :elegir, on: :member
  end

	get '/auction/myAuctions', to: 'auctions#myAuctions'
  get '/auction/finalizar', to: 'auctions#finalizar'
  get '/auction/finalizadas', to: 'auctions#finalizadas'
  get '/auction/ganadas', to: 'auctions#ganadas'

  resources :categories

  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout	

end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_filter :require_login, except: [:destroy]
  # skip_before_filter :require_login, except: [:destroy], except: [:auctions]

  def new
  	@user = User.new
  end

  def create
    if User.where(username: params[:username], active: true).blank?
      flash.keep[:alert] = 'El usuario no existe o no se encuentra activo'
      render action: 'new'
    elsif @user = login(params[:username], params[:password], params[:remember_me])
      redirect_to(auctions_path, notice: '¡Has iniciado sesión!')
    else
      flash.keep[:alert] = 'Nombre de usuario o contraseña incorrectos'
      render action: 'new'  
    end
  end

  def destroy
  	logout
  	redirect_to(:auctions, notice: '¡Has cerrado sesión!')
  end
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/views/user_sessions/_form.html.erb
<%= form_tag user_sessions_path, :method => :post do %>

	<div class="form-group">
		<%= label_tag :username, "Nombre de usuario" %>
		<%= text_field_tag :username, nil,  :class => 'form-control' %>
	</div>

	<div class="form-group">
		<%= label_tag :password, "Contraseña" %>
		<%= password_field_tag :password, nil, :class => 'form-control' %>
	</div>

	<div class="form-group">
		<%= check_box_tag :remember_me, 1, params[:remember_me] %>
		<%= label_tag :remember_me, "No cerrar sesión" %>
	</div>	

	<div class="actions">
		<%= submit_tag "Ingresar", id: "myButton", class: "btn btn-primary", data: {"loading-text" => "Espere..."} %>
		<%= link_to '¿Olvidaste tu contraseña?', new_password_reset_path %>
	</div>
<% end %>

<script>
  $("#myButton").click(function() {
    var $btn = $(this);
    $btn.button('loading');
    // simulating a timeout
    setTimeout(function () {
        $btn.button('reset');
    }, 1000);
	});
</script>

app/views/user_sessions/create.html.erb
<h1>Crear Sesión de Usuario</h1>
<p>Find me in app/views/user_sessions/create.html.erb</p>

app/views/user_sessions/destroy.html.erb
<h1>Destruir Sesión de Usuario</h1>
<p>Find me in app/views/user_sessions/destroy.html.erb</p>

app/views/user_sessions/new.html.erb
<h1>Ingresar a Mi cuenta</h1>

<%= render 'form' %>